<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Assets\Themes\*.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="Assets\Sounds\*.wav" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
